way_points: p0

p1:
  x: 0.0
  y: 0.0
  z: 0.0

p1:
  x: 11.6
  y: -1.7
  z: 0.0

p2:
  x: 18.1
  y: -19.0
  z: 0.0

p3:
  x: 9.0
  y: -24.8
  z: 0.0

p4:
  x: 16.5
  y: -37.3
  z: 0.0

p5:
  x: 5.1
  y: -45.3
  z: 0.0 

p6:
  x: 0.5
  y: -61.3
  z: 0.0

p7:
  x: 4.7
  y: -72.9
  z: 0.0

p8:
  x: -2.6
  y: -83.8
  z: 0.0

p9:
  x: -3.0
  y: -98.3
  z: 0.0

p9a:
  x: -6.3
  y: -109.1
  z: 0.0

p10:
  x: -15.2
  y: -117.3
  z: 2.93


